CREATE TABLE IF NOT EXISTS ingredientes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(120) UNIQUE NOT NULL,
  stock DECIMAL(10,2) NOT NULL DEFAULT 0,
  unidad VARCHAR(20) NOT NULL,
  stock_minimo DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_nombre (nombre),
  INDEX idx_stock (stock)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
